import type { Usuario, Estudiante, TipoFalta, Infraccion } from './types';

// ── Usuarios ────────────────────────────────────────────────────────────────
export const mockUsuarios: Usuario[] = [
  {
    id: 'u1',
    email: 'admin@colegiodorado.edu',
    nombre_completo: 'Carlos Mendoza',
    rol: 'admin',
    avatar_url: null,
    created_at: '2024-01-15T08:00:00Z',
  },
  {
    id: 'u2',
    email: 'regente.garcia@colegiodorado.edu',
    nombre_completo: 'María García',
    rol: 'regente',
    avatar_url: null,
    created_at: '2024-02-01T09:00:00Z',
  },
  // Cuentas de estudiantes — se identifican con su código (campo email)
  {
    id: 'ue1',
    email: '202601',
    nombre_completo: 'Alejandro Rodríguez',
    rol: 'estudiante',
    avatar_url: null,
    created_at: '2024-01-20T08:00:00Z',
    estudiante_id: 'e1',
  },
  {
    id: 'ue2',
    email: '1002',
    nombre_completo: 'Valentina Sánchez',
    rol: 'estudiante',
    avatar_url: null,
    created_at: '2024-01-20T08:00:00Z',
    estudiante_id: 'e2',
  },
  {
    id: 'ue3',
    email: '1003',
    nombre_completo: 'Santiago Herrera',
    rol: 'estudiante',
    avatar_url: null,
    created_at: '2024-01-20T08:00:00Z',
    estudiante_id: 'e3',
  },
];

// ── Estudiantes (cursos 1ro–6to, secciones A/B/C) ───────────────────────────
export const mockEstudiantes: Estudiante[] = [
  {
    id: 'e1',
    nombre_completo: 'Alejandro Rodríguez',
    curso: '4to',
    seccion: 'A',
    direccion: 'Calle 45 #12-34, Bogotá',
    foto_url: null,
    activo: true,
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'e2',
    nombre_completo: 'Valentina Sánchez',
    curso: '3ro',
    seccion: 'B',
    direccion: 'Av. Libertador 567, Bogotá',
    foto_url: null,
    activo: true,
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'e3',
    nombre_completo: 'Santiago Herrera',
    curso: '5to',
    seccion: 'A',
    direccion: 'Carrera 10 #45-67, Bogotá',
    foto_url: null,
    activo: true,
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'e4',
    nombre_completo: 'Isabella Torres',
    curso: '4to',
    seccion: 'B',
    direccion: 'Calle 72 #89-12, Bogotá',
    foto_url: null,
    activo: true,
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'e5',
    nombre_completo: 'Mateo Gómez',
    curso: '6to',
    seccion: 'A',
    direccion: 'Transversal 3 #15-28, Bogotá',
    foto_url: null,
    activo: true,
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'e6',
    nombre_completo: 'Luciana Vargas',
    curso: '2do',
    seccion: 'C',
    direccion: 'Diagonal 56 #78-90, Bogotá',
    foto_url: null,
    activo: true,
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'e7',
    nombre_completo: 'Daniel Morales',
    curso: '1ro',
    seccion: 'B',
    direccion: 'Calle 100 #23-45, Bogotá',
    foto_url: null,
    activo: false,
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'e8',
    nombre_completo: 'Camila Ruiz',
    curso: '3ro',
    seccion: 'C',
    direccion: 'Av. Boyacá 34-56, Bogotá',
    foto_url: null,
    activo: true,
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'e9',
    nombre_completo: 'Sebastián Castro',
    curso: '5to',
    seccion: 'B',
    direccion: 'Carrera 7 #132-45, Bogotá',
    foto_url: null,
    activo: true,
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'e10',
    nombre_completo: 'Sofía Ramírez',
    curso: '4to',
    seccion: 'C',
    direccion: 'Calle 26 #67-89, Bogotá',
    foto_url: null,
    activo: true,
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'e11',
    nombre_completo: 'Andrés Peña',
    curso: '1ro',
    seccion: 'A',
    direccion: 'Cra 15 #45-23, Bogotá',
    foto_url: null,
    activo: true,
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'e12',
    nombre_completo: 'María Fernanda Ríos',
    curso: '2do',
    seccion: 'A',
    direccion: 'Calle 50 #12-67, Bogotá',
    foto_url: null,
    activo: true,
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'e13',
    nombre_completo: 'Felipe Ortega',
    curso: '6to',
    seccion: 'C',
    direccion: 'Av. El Dorado #30-45, Bogotá',
    foto_url: null,
    activo: true,
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'e14',
    nombre_completo: 'Valeria Mendoza',
    curso: '1ro',
    seccion: 'C',
    direccion: 'Cra 30 #22-11, Bogotá',
    foto_url: null,
    activo: true,
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'e15',
    nombre_completo: 'Carlos Jiménez',
    curso: '6to',
    seccion: 'B',
    direccion: 'Calle 80 #55-33, Bogotá',
    foto_url: null,
    activo: true,
    created_at: '2024-01-20T08:00:00Z',
  },
];

// ── Tipos de Falta ──────────────────────────────────────────────────────────
// Las 4 leves son las únicas que puede registrar el regente
export const mockTiposFalta: TipoFalta[] = [
  {
    id: 'tf1',
    nombre: 'Retraso',
    descripcion: 'El estudiante llega tarde al inicio de clases o después del cambio de hora',
    gravedad: 'leve',
    color: '#22c55e',
  },
  {
    id: 'tf2',
    nombre: 'Falta',
    descripcion: 'Ausencia del estudiante sin justificación válida presentada al regente',
    gravedad: 'leve',
    color: '#22c55e',
  },
  {
    id: 'tf3',
    nombre: 'Uso de celular',
    descripcion: 'Uso no autorizado de dispositivos móviles durante clase o evaluación',
    gravedad: 'leve',
    color: '#22c55e',
  },
  {
    id: 'tf4',
    nombre: 'Uniforme',
    descripcion: 'No portar el uniforme escolar completo según el reglamento interno',
    gravedad: 'leve',
    color: '#22c55e',
  },
  {
    id: 'tf5',
    nombre: 'Conducta disruptiva',
    descripcion: 'Comportamiento que interrumpe el normal desarrollo de la clase',
    gravedad: 'grave',
    color: '#eab308',
  },
  {
    id: 'tf6',
    nombre: 'Copia en examen',
    descripcion: 'Fraude académico durante evaluaciones escritas u orales',
    gravedad: 'grave',
    color: '#eab308',
  },
  {
    id: 'tf7',
    nombre: 'Daño a propiedad',
    descripcion: 'Deterioro intencional de instalaciones o materiales del colegio',
    gravedad: 'grave',
    color: '#eab308',
  },
  {
    id: 'tf8',
    nombre: 'Agresión física',
    descripcion: 'Violencia física contra otro estudiante o miembro del personal',
    gravedad: 'muy_grave',
    color: '#ef4444',
  },
  {
    id: 'tf9',
    nombre: 'Bullying',
    descripcion: 'Acoso sistemático hacia otro estudiante de forma verbal, física o digital',
    gravedad: 'muy_grave',
    color: '#ef4444',
  },
];

// Tipos de falta que puede registrar el regente (solo leves)
export const tiposFaltaRegente = mockTiposFalta.filter((tf) => tf.gravedad === 'leve');

// ── Infracciones (sin campo estado) ────────────────────────────────────────
export const mockInfracciones: Infraccion[] = [
  {
    id: 'i1',
    estudiante_id: 'e1',
    regente_id: 'u2',
    tipo_falta_id: 'tf1',
    fecha: '2024-11-05',
    descripcion: 'El estudiante llegó 20 minutos tarde a la primera hora sin justificación.',
    created_at: '2024-11-05T07:20:00Z',
  },
  {
    id: 'i2',
    estudiante_id: 'e3',
    regente_id: 'u3',
    tipo_falta_id: 'tf5',
    fecha: '2024-11-08',
    descripcion:
      'Interrumpió repetidamente la clase de matemáticas molestando a sus compañeros.',
    created_at: '2024-11-08T10:30:00Z',
  },
  {
    id: 'i3',
    estudiante_id: 'e2',
    regente_id: 'u2',
    tipo_falta_id: 'tf3',
    fecha: '2024-11-10',
    descripcion: 'Se encontró a la estudiante usando el celular durante el examen de ciencias.',
    created_at: '2024-11-10T09:15:00Z',
  },
  {
    id: 'i4',
    estudiante_id: 'e5',
    regente_id: 'u4',
    tipo_falta_id: 'tf8',
    fecha: '2024-11-12',
    descripcion: 'Inició una pelea en el patio durante el recreo causando lesiones menores.',
    created_at: '2024-11-12T11:45:00Z',
  },
  {
    id: 'i5',
    estudiante_id: 'e4',
    regente_id: 'u3',
    tipo_falta_id: 'tf6',
    fecha: '2024-11-15',
    descripcion: 'Copiaba de un compañero durante el examen de historia.',
    created_at: '2024-11-15T14:20:00Z',
  },
  {
    id: 'i6',
    estudiante_id: 'e1',
    regente_id: 'u4',
    tipo_falta_id: 'tf4',
    fecha: '2024-11-18',
    descripcion: 'Sin la camiseta del uniforme reglamentario por segunda vez en la semana.',
    created_at: '2024-11-18T07:05:00Z',
  },
  {
    id: 'i7',
    estudiante_id: 'e8',
    regente_id: 'u2',
    tipo_falta_id: 'tf9',
    fecha: '2024-11-20',
    descripcion:
      'Múltiples incidentes de acoso verbal hacia una compañera durante varias semanas.',
    created_at: '2024-11-20T16:00:00Z',
  },
  {
    id: 'i8',
    estudiante_id: 'e9',
    regente_id: 'u3',
    tipo_falta_id: 'tf7',
    fecha: '2024-11-22',
    descripcion: 'Rayó las paredes del salón con marcador permanente intencionalmente.',
    created_at: '2024-11-22T13:30:00Z',
  },
  {
    id: 'i9',
    estudiante_id: 'e1',
    regente_id: 'u2',
    tipo_falta_id: 'tf1',
    fecha: '2024-11-25',
    descripcion: 'Llegó 15 minutos tarde después del cambio de hora.',
    created_at: '2024-11-25T08:15:00Z',
  },
  {
    id: 'i10',
    estudiante_id: 'e6',
    regente_id: 'u2',
    tipo_falta_id: 'tf5',
    fecha: '2024-11-28',
    descripcion: 'Se negó a seguir instrucciones y respondió de manera irrespetuosa.',
    created_at: '2024-11-28T10:00:00Z',
  },
  {
    id: 'i11',
    estudiante_id: 'e1',
    regente_id: 'u2',
    tipo_falta_id: 'tf1',
    fecha: '2024-12-01',
    descripcion: 'Tercer retraso del mes, llegó 25 minutos tarde sin justificar.',
    created_at: '2024-12-01T07:10:00Z',
  },
  {
    id: 'i12',
    estudiante_id: 'e2',
    regente_id: 'u3',
    tipo_falta_id: 'tf2',
    fecha: '2024-12-03',
    descripcion: 'Ausencia no justificada a la clase de matemáticas.',
    created_at: '2024-12-03T08:00:00Z',
  },
  {
    id: 'i19',
    estudiante_id: 'e14',
    regente_id: 'u3',
    tipo_falta_id: 'tf2',
    fecha: '2024-12-03',
    descripcion: 'Ausencia no justificada a la clase de matemáticas.',
    created_at: '2024-12-03T08:00:00Z',
  },
];

// ── Helpers ──────────────────────────────────────────────────────────────────
export function getInfraccionesConDatos(): Infraccion[] {
  return mockInfracciones.map((inf) => ({
    ...inf,
    estudiante: mockEstudiantes.find((e) => e.id === inf.estudiante_id),
    regente: mockUsuarios.find((u) => u.id === inf.regente_id),
    tipo_falta: mockTiposFalta.find((tf) => tf.id === inf.tipo_falta_id),
  }));
}

export function getEstudianteInfracciones(estudianteId: string): Infraccion[] {
  return getInfraccionesConDatos().filter((inf) => inf.estudiante_id === estudianteId);
}

export function getRetrasoCount(estudianteId: string): number {
  return mockInfracciones.filter(
    (inf) => inf.estudiante_id === estudianteId && inf.tipo_falta_id === 'tf1',
  ).length;
}
